name: Vivek Spell Check Automation

on:
  pull_request:
  push:

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # See: https://github.com/codespell-project/actions-codespell/blob/master/README.md
      - name: Spell check
        uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          check_hidden: true
